### ISSUE TITLE
How to predict new images with pre-trained model. 

### ISSUE THREAD

**Issue by trlnoe** [Tsingularity/FRN#11] opened 2022-08-08 07:41 UTC
Assuming I have a new image without labeling it into any class id, what should I modify the given code to gain the right class id with your suggested model? Your solution seems very appropriate to my problems, and I truly hope that I could apply it precisely to mine, so   I really look forward to your answer! Thank you in advance!

**Comment by Tsingularity** [comment] 2022-08-08 20:54
Hi, thanks for ur interest in our work!

Since this codebase is mainly intend for reproducing the training and evaluation of our proposed method, it might be a bit hard to adapt it to a single demo showcase.

I think you can refer to the `meta_test()` [function](https://github.com/Tsingularity/FRN/blob/15d84832ca39a33beb7617cb7a577851e62cb861/trainers/eval.py#L19) we used during evaluation. If you replaced the dataloader with yours (or replace the per-episode `inp` tensor with your post-processed data tensors), it should be fine. But it should be noted that, in addition the query images, you also need to give the few-shot support images as part of the input (more details could be found in our dataloader [sampler](https://github.com/Tsingularity/FRN/blob/15d84832ca39a33beb7617cb7a577851e62cb861/datasets/samplers.py#L55) and model [meta_test](https://github.com/Tsingularity/FRN/blob/main/models/FRN.py#L115) functions.)

Feel free to let us know if u have more questions.

**Comment by Tsingularity** [comment] 2022-08-16 18:17
Closing for now. Feel free to reopen if u have more questions.

**Closed as completed** 2022-08-16 18:18 UTC

**Comment by trlnoe** [comment] 2022-08-19 00:42
> 

Thank you so much! It's really helpful for my cases.

**Comment by 0-Maxwei-0** [comment] 2023-04-06 12:01
> > 
> 
> Thank you so much! It's really helpful for my cases.

hello! I have the same question as you. Can you share some details about how you solved this?
